"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { EmojiPicker } from "@/components/messages/EmojiPicker";
import { MessageBubble, type ChatBubbleMessage } from "@/components/messages/MessageBubble";
import { Avatar } from "@/components/ui/Avatar";
import { BackButton } from "@/components/ui/BackLink";
import { EmptyState } from "@/components/ui/EmptyState";
import { Icon } from "@/components/ui/Icon";
import { useAuth } from "@/lib/auth-context";
import { formatRelativeTime } from "@/lib/profile";
import { fetchMessageReactions, openDirectMessage, sendConversationMessage, toggleMessageReaction } from "@/lib/social";
import { createClient } from "@/lib/supabase/client";

type ConversationItem={id:string;name:string;avatar:string;preview:string;time:string;unread:boolean};
type MessageItem=ChatBubbleMessage;
const audioUrl=(path?:string|null)=>path?createClient()?.storage.from("message-audio").getPublicUrl(path).data.publicUrl:null;
function isUnread(lastAt?:string,lastReadAt?:string|null,lastFromMe?:boolean){if(!lastAt||lastFromMe)return false;if(!lastReadAt)return true;return new Date(lastAt).getTime()>new Date(lastReadAt).getTime()}
function fmt(s:number){return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`}

export function MessagesInbox({queryId,toId}:{queryId:string|null;toId:string|null}){
 const {user,loading:authLoading}=useAuth(); const router=useRouter();
 const [conversations,setConversations]=useState<ConversationItem[]>([]),[activeId,setActiveId]=useState<string|null>(queryId),[messages,setMessages]=useState<MessageItem[]>([]),[draft,setDraft]=useState(""),[filter,setFilter]=useState<"All"|"Unread">("All"),[loadingList,setLoadingList]=useState(true),[loadingThread,setLoadingThread]=useState(false),[error,setError]=useState<string|null>(null),[sendError,setSendError]=useState<string|null>(null),[pickerOpen,setPickerOpen]=useState(false),[reactionBarId,setReactionBarId]=useState<string|null>(null),[recording,setRecording]=useState(false),[recordSeconds,setRecordSeconds]=useState(0),[sendingVoice,setSendingVoice]=useState(false);
 const draftRef=useRef<HTMLInputElement>(null),pandaBtnRef=useRef<HTMLButtonElement>(null),recorderRef=useRef<MediaRecorder|null>(null),streamRef=useRef<MediaStream|null>(null),chunksRef=useRef<Blob[]>([]),timerRef=useRef<ReturnType<typeof setInterval>|null>(null);
 const openThread=useCallback((id:string|null)=>{setActiveId(id);router.replace(id?`/messages?c=${id}`:"/messages",{scroll:false})},[router]);
 const loadConversations=useCallback(async()=>{const s=createClient();if(!s||!user){setLoadingList(false);setError(s?null:"Messaging is not configured.");return}const {data:ms,error:e}=await s.from("conversation_members").select("conversation_id, last_read_at").eq("user_id",user.id);if(e){setError(e.message);setLoadingList(false);return}const ids=(ms??[]).map(r=>r.conversation_id as string);if(!ids.length){setConversations([]);setLoadingList(false);return}const [{data:members},{data:last}]=await Promise.all([s.from("conversation_members").select("conversation_id, user_id, profiles(full_name, avatar_url)").in("conversation_id",ids),s.from("messages").select("id, conversation_id, sender_id, content, audio_path, created_at").in("conversation_id",ids).order("created_at",{ascending:false})]);setConversations(ids.map(id=>{const m=(ms??[]).find(r=>r.conversation_id===id),other=(members??[]).find(x=>x.conversation_id===id&&x.user_id!==user.id),p=(other?.profiles&&(Array.isArray(other.profiles)?other.profiles[0]:other.profiles)) as {full_name?:string;avatar_url?:string}|undefined,l=(last??[]).find(x=>x.conversation_id===id);return{id,name:p?.full_name||"SheRides chat",avatar:p?.avatar_url||"",preview:l?.audio_path?"🎙️ Voice message":l?.content||"No messages yet",time:formatRelativeTime(l?.created_at as string|undefined),unread:isUnread(l?.created_at as string|undefined,m?.last_read_at as string|null,l?.sender_id===user.id)}}));setError(null);setLoadingList(false)},[user]);
 useEffect(()=>{void loadConversations()},[loadConversations]);
 useEffect(()=>{if(queryId&&queryId!==activeId)setActiveId(queryId)},[queryId,activeId]);
 useEffect(()=>{if(!toId||!user||queryId)return;if(toId===user.id){setSendError("You cannot message yourself.");return}const s=createClient();if(!s)return;let cancelled=false;void openDirectMessage(s,toId).then(({id,error:e})=>{if(cancelled)return;if(!id){setSendError(e||"Could not open that conversation.");return}setActiveId(id);router.replace(`/messages?c=${id}`,{scroll:false});void loadConversations()});return()=>{cancelled=true}},[toId,queryId,user,router,loadConversations]);
 useEffect(()=>{const s=createClient();if(!s||!user||!activeId){setMessages([]);return}let cancelled=false;setLoadingThread(true);void s.from("messages").select("id, sender_id, content, audio_path, audio_duration_seconds, created_at").eq("conversation_id",activeId).order("created_at",{ascending:true}).then(async({data,error:e})=>{if(cancelled)return;if(e){setSendError(e.message);setLoadingThread(false);return}const rows=data??[],rx=await fetchMessageReactions(s,rows.map(r=>r.id as string)),map=new Map<string,ChatBubbleMessage["reactions"]>();for(const r of rx.rows){const l=map.get(r.message_id)??[];l.push({emoji:r.emoji,userId:r.user_id});map.set(r.message_id,l)}setMessages(rows.map(r=>({id:r.id as string,fromMe:r.sender_id===user.id,text:(r.content as string)||"",audioUrl:audioUrl(r.audio_path as string|null),audioDuration:r.audio_duration_seconds as number|null,time:formatRelativeTime(r.created_at as string),reactions:map.get(r.id as string)??[]})));setLoadingThread(false);await s.from("conversation_members").update({last_read_at:new Date().toISOString()}).eq("conversation_id",activeId).eq("user_id",user.id)});const ch=s.channel(`messages:${activeId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${activeId}`},payload=>{const r=payload.new as {id:string;sender_id:string;content?:string;audio_path?:string;audio_duration_seconds?:number;created_at:string};setMessages(p=>p.some(x=>x.id===r.id)?p:[...p,{id:r.id,fromMe:r.sender_id===user.id,text:r.content||"",audioUrl:audioUrl(r.audio_path),audioDuration:r.audio_duration_seconds,time:formatRelativeTime(r.created_at),reactions:[]}]);setConversations(p=>p.map(c=>c.id===activeId?{...c,preview:r.audio_path?"🎙️ Voice message":r.content||c.preview,time:"Just now",unread:r.sender_id!==user.id}:c))}).subscribe();return()=>{cancelled=true;void s.removeChannel(ch)}},[activeId,user]);
 useEffect(()=>{setPickerOpen(false);setReactionBarId(null)},[activeId]);
 useEffect(()=>()=>{if(timerRef.current)clearInterval(timerRef.current);streamRef.current?.getTracks().forEach(t=>t.stop())},[]);
 const active=conversations.find(c=>c.id===activeId),list=useMemo(()=>conversations.filter(c=>filter==="Unread"?c.unread:true),[conversations,filter]);
 async function send(){const text=draft.trim(),s=createClient();if(!text||!s||!user||!activeId)return;setDraft("");const {id,error:e}=await sendConversationMessage(s,activeId,user.id,text);if(!id){setDraft(text);setSendError(e||"Message could not be sent.");return}setMessages(p=>p.some(x=>x.id===id)?p:[...p,{id,fromMe:true,text,time:"Just now",reactions:[]}]);setPickerOpen(false)}
 async function startRecording(){if(!user||!activeId||!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setSendError("Voice recording is not supported on this device/browser.");return}try{setSendError(null);const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const preferred=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"";const rec=new MediaRecorder(stream,preferred?{mimeType:preferred}:undefined);recorderRef.current=rec;chunksRef.current=[];setRecordSeconds(0);rec.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};rec.onstop=()=>void finishVoice(rec.mimeType||"audio/webm");rec.start();setRecording(true);timerRef.current=setInterval(()=>setRecordSeconds(v=>{if(v>=179){rec.stop();return 180}return v+1}),1000)}catch{setSendError("Microphone permission is required to record a voice message.")}}
 function stopRecording(){if(recorderRef.current?.state==="recording")recorderRef.current.stop()}
 function cancelRecording(){const rec=recorderRef.current;if(rec){rec.onstop=null;if(rec.state==="recording")rec.stop()}chunksRef.current=[];cleanupRecorder()}
 function cleanupRecorder(){if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null}streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;recorderRef.current=null;setRecording(false);setRecordSeconds(0)}
 async function finishVoice(mime:string){const seconds=Math.max(1,recordSeconds),blob=new Blob(chunksRef.current,{type:mime}),s=createClient();cleanupRecorder();if(!s||!user||!activeId||!blob.size)return;setSendingVoice(true);const ext=mime.includes("mp4")?"m4a":mime.includes("ogg")?"ogg":"webm",path=`${user.id}/${activeId}/${Date.now()}.${ext}`;const up=await s.storage.from("message-audio").upload(path,blob,{contentType:mime,upsert:false});if(up.error){setSendError(up.error.message);setSendingVoice(false);return}const ins=await s.from("messages").insert({conversation_id:activeId,sender_id:user.id,content:"",audio_path:path,audio_duration_seconds:seconds}).select("id, created_at").single();if(ins.error){await s.storage.from("message-audio").remove([path]);setSendError(ins.error.message);setSendingVoice(false);return}setMessages(p=>p.some(x=>x.id===ins.data.id)?p:[...p,{id:ins.data.id,fromMe:true,text:"",audioUrl:audioUrl(path),audioDuration:seconds,time:"Just now",reactions:[]}]);setSendingVoice(false)}
 function insertEmoji(e:string){const el=draftRef.current,start=el?.selectionStart??draft.length,end=el?.selectionEnd??draft.length;setDraft(draft.slice(0,start)+e+draft.slice(end));requestAnimationFrame(()=>el?.focus())}
 async function reactTo(id:string,emoji:string){const s=createClient();if(!s||!user)return;const on=messages.find(x=>x.id===id)?.reactions.some(r=>r.userId===user.id&&r.emoji===emoji);setMessages(p=>p.map(x=>x.id!==id?x:{...x,reactions:on?x.reactions.filter(r=>!(r.userId===user.id&&r.emoji===emoji)):[...x.reactions,{userId:user.id,emoji}]}));const e=await toggleMessageReaction(s,id,user.id,emoji,Boolean(on));if(e)setSendError(e)}
 if(authLoading&&!user)return <p className="p-6 font-body-sm text-tertiary">Loading messages…</p>;
 if(!user)return <div className="max-w-2xl mx-auto p-6"><EmptyState title="Sign in to read messages." body="Your SheRides conversations stay private." /></div>;
 return <div className="lg:p-6 p-0 max-w-[1600px] mx-auto h-full min-h-[480px]"><div className="flex bg-surface-container-lowest lg:rounded-xl lg:shadow-premium border-y lg:border border-surface-border overflow-hidden w-full h-full">
  <div className={`${activeId&&"hidden md:flex"} w-full md:w-[320px] xl:w-[360px] flex-shrink-0 border-r border-surface-border bg-soft-off-white flex flex-col h-full`}><div className="p-4 border-b border-surface-border bg-surface-container-lowest"><h1 className="font-headline-md text-headline-md mb-4">Messages</h1><div className="flex gap-2">{(["All","Unread"] as const).map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-3 py-1 rounded-full ${filter===f?"bg-primary-fixed-dim":"bg-surface-container-high"}`}>{f}</button>)}</div></div><div className="flex-1 overflow-y-auto">{loadingList&&<p className="p-6 text-tertiary">Loading conversations…</p>}{error&&<p className="p-6 text-error">{error}</p>}{list.map(c=><button key={c.id} onClick={()=>openThread(c.id)} className={`w-full flex items-center gap-3 p-4 text-left border-l-4 ${c.id===activeId?"bg-surface border-accent-magenta":"border-transparent"}`}><Avatar src={c.avatar} alt={c.name} size={48}/><div className="flex-1 min-w-0"><div className="flex justify-between"><b className="truncate">{c.name}</b><span className="text-[11px]">{c.time}</span></div><p className="text-sm truncate text-secondary">{c.preview}</p></div>{c.unread&&<span className="h-2.5 w-2.5 rounded-full bg-accent-magenta"/>}</button>)}</div></div>
  <div className={`${!activeId&&"hidden"} md:flex flex-1 flex-col h-full bg-surface-container-lowest`}>{!activeId?<div className="flex-1 flex items-center justify-center"><EmptyState variant="messages" title="Your messages live here." body="Start a conversation with a rider."/></div>:<><div className="flex items-center gap-3 p-4 border-b"><BackButton className="md:hidden" onClick={()=>openThread(null)} label="Chats"/><Avatar src={active?.avatar} alt={active?.name??"Chat"} size={40}/><h2 className="font-label-lg">{active?.name||"Conversation"}</h2></div><div className="flex-1 overflow-y-auto p-6 pt-12 space-y-4 bg-soft-off-white">{loadingThread&&<p>Loading messages…</p>}{messages.map(m=><MessageBubble key={m.id} message={m} currentUserId={user.id} barOpen={reactionBarId===m.id} onToggleBar={()=>setReactionBarId(x=>x===m.id?null:m.id)} onToggleReaction={e=>void reactTo(m.id,e)}/>)}</div><div className="p-4 border-t">{sendError&&<p className="mb-2 text-sm text-error">{sendError}</p>}{recording?<div className="flex items-center gap-3 rounded-full border border-accent-magenta px-4 py-2"><span className="h-2.5 w-2.5 rounded-full bg-red-500 animate-pulse"/><span className="font-semibold flex-1">Recording {fmt(recordSeconds)}</span><button onClick={cancelRecording} className="px-3 py-1">Cancel</button><button onClick={stopRecording} className="px-4 py-2 rounded-full bg-accent-magenta text-white">Send</button></div>:<div className="relative"><EmojiPicker open={pickerOpen} onClose={()=>setPickerOpen(false)} onSelect={insertEmoji} ignoreRef={pandaBtnRef}/><div className="flex items-center gap-2 bg-soft-off-white border rounded-full px-2 py-1"><button ref={pandaBtnRef} onClick={()=>setPickerOpen(x=>!x)} className="h-9 w-9">🐼</button><input ref={draftRef} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}} className="flex-1 bg-transparent focus:outline-none px-2 py-2" placeholder="Type a message..."/>{!draft.trim()?<button disabled={sendingVoice} onClick={()=>void startRecording()} className="p-2 rounded-full hover:bg-surface-container-high" aria-label="Record voice message"><Icon name="mic" size={22}/></button>:null}<button onClick={()=>void send()} className="p-2 bg-accent-magenta text-white rounded-full"><Icon name="send" size={20}/></button></div>{sendingVoice&&<p className="text-xs text-tertiary mt-1">Sending voice message…</p>}</div>}</div></>}</div>
 </div></div>
}
