import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        tertiary: "#5a5c5d",
        "surface-dim": "#dadada",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffd9de",
        "soft-off-white": "#F8F9FA",
        "deep-charcoal": "#1A1C1E",
        "primary-fixed-dim": "#ffb2be",
        background: "#f9f9f9",
        "surface-container": "#eeeeee",
        "inverse-primary": "#ffb2be",
        "inverse-on-surface": "#f0f1f1",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#454748",
        "surface-variant": "#e2e2e2",
        "surface-container-low": "#f3f3f4",
        "tertiary-fixed": "#e1e3e4",
        surface: "#f9f9f9",
        "secondary-fixed-dim": "#c6c6c9",
        primary: "#b80049",
        "on-tertiary-container": "#fcfdfe",
        "accent-magenta": "#E91E63",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-fixed": "#191c1d",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed": "#1a1c1e",
        "on-surface-variant": "#5b3f43",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#454749",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f3131",
        "outline-variant": "#e4bdc2",
        "on-secondary-container": "#636467",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-bright": "#f9f9f9",
        secondary: "#5d5e61",
        "secondary-container": "#e2e2e5",
        "on-primary-fixed": "#400014",
        "on-primary": "#ffffff",
        "tertiary-container": "#737576",
        "surface-container-highest": "#e2e2e2",
        "surface-border": "#E9ECEF",
        "primary-container": "#e2165f",
        "on-error-container": "#93000a",
        "secondary-fixed": "#e2e2e5",
        "on-primary-fixed-variant": "#900038",
        "surface-tint": "#bc004b",
        outline: "#8f6f73",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "64px",
        gutter: "24px",
        "container-margin-mobile": "24px",
        "component-gap": "16px",
        base: "8px",
        "container-margin-desktop": "80px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-xl": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "label-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg-mobile": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["34px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        premium: "0px 10px 30px rgba(26, 28, 30, 0.05)",
        "premium-hover": "0px 15px 40px rgba(26, 28, 30, 0.08)",
        nav: "0px 4px 20px rgba(0, 0, 0, 0.1)",
        "bottom-nav": "0px -4px 16px rgba(0, 0, 0, 0.05)",
        magenta: "0px 10px 20px rgba(233, 30, 99, 0.2)",
      },
    },
  },
  plugins: [],
};

export default config;
