import type { Config } from "tailwindcss";

function withOpacity(variable: string): string {
  const resolver = ({ opacityValue }: { opacityValue?: string }) =>
    opacityValue === undefined ? `rgb(var(${variable}))` : `rgb(var(${variable}) / ${opacityValue})`;
  return resolver as unknown as string;
}

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        tertiary: withOpacity("--color-tertiary"),
        "surface-dim": withOpacity("--color-surface-dim"),
        "on-background": withOpacity("--color-on-surface"),
        "error-container": "#ffdad6",
        "primary-fixed": "#ffd9de",
        "soft-off-white": withOpacity("--color-soft-off-white"),
        "deep-charcoal": "#1A1C1E",
        "primary-fixed-dim": "#ffb2be",
        background: withOpacity("--color-surface"),
        "surface-container": withOpacity("--color-surface-container"),
        "inverse-primary": "#ffb2be",
        "inverse-on-surface": "#f0f1f1",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#454748",
        "surface-variant": withOpacity("--color-surface-variant"),
        "surface-container-low": withOpacity("--color-surface-container-low"),
        "tertiary-fixed": "#e1e3e4",
        surface: withOpacity("--color-surface"),
        "secondary-fixed-dim": "#c6c6c9",
        primary: "#b80049",
        "on-tertiary-container": "#fcfdfe",
        "accent-magenta": "#E91E63",
        "surface-container-high": withOpacity("--color-surface-container-high"),
        "on-tertiary-fixed": "#191c1d",
        "on-surface": withOpacity("--color-on-surface"),
        "on-secondary-fixed": "#1a1c1e",
        "on-surface-variant": "#5b3f43",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#454749",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-lowest": withOpacity("--color-surface-container-lowest"),
        "inverse-surface": "#2f3131",
        "outline-variant": "#e4bdc2",
        "on-secondary-container": "#636467",
        "tertiary-fixed-dim": "#c5c7c8",
        "surface-bright": "#f9f9f9",
        secondary: withOpacity("--color-secondary"),
        "secondary-container": "#e2e2e5",
        "on-primary-fixed": "#400014",
        "on-primary": "#ffffff",
        "tertiary-container": "#737576",
        "surface-container-highest": "#e2e2e2",
        "surface-border": withOpacity("--color-surface-border"),
        "primary-container": "#e2165f",
        "on-error-container": "#93000a",
        "secondary-fixed": "#e2e2e5",
        "on-primary-fixed-variant": "#900038",
        "surface-tint": "#bc004b",
        outline: withOpacity("--color-outline"),
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "64px",
        gutter: "24px",
        "container-margin-mobile": "24px",
        "component-gap": "16px",
        base: "8px",
        "container-margin-desktop": "80px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-xl": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "label-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg-mobile": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["34px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        premium: "0px 10px 30px rgba(26, 28, 30, 0.05)",
        "premium-hover": "0px 15px 40px rgba(26, 28, 30, 0.08)",
        nav: "0px 4px 20px rgba(0, 0, 0, 0.1)",
        "bottom-nav": "0px -4px 16px rgba(0, 0, 0, 0.05)",
        magenta: "0px 10px 20px rgba(233, 30, 99, 0.2)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-400px 0" },
          "100%": { backgroundPosition: "400px 0" },
        },
        "ring-spin": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "badge-pop": {
          "0%": { transform: "scale(0.5)", opacity: "0" },
          "60%": { transform: "scale(1.15)", opacity: "1" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "heart-pop": {
          "0%": { transform: "scale(1)" },
          "35%": { transform: "scale(1.4)" },
          "60%": { transform: "scale(0.9)" },
          "100%": { transform: "scale(1)" },
        },
        "sos-pulse": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(233, 30, 99, 0.45)", transform: "scale(1)" },
          "70%": { boxShadow: "0 0 0 14px rgba(233, 30, 99, 0)", transform: "scale(1.03)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.5s cubic-bezier(0.16, 1, 0.3, 1) both",
        "fade-in": "fade-in 0.4s ease-out both",
        "scale-in": "scale-in 0.25s cubic-bezier(0.16, 1, 0.3, 1) both",
        shimmer: "shimmer 1.6s ease-in-out infinite",
        "ring-spin-slow": "ring-spin 6s linear infinite",
        "badge-pop": "badge-pop 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        "heart-pop": "heart-pop 0.4s ease-out",
        "sos-pulse": "sos-pulse 1.8s ease-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
