import { img } from "./images";
import type {
  AppNotification,
  ChatMessage,
  Community,
  Conversation,
  FeedPost,
  Hashtag,
  RideEvent,
  Rider,
  Story,
} from "./types";

export const currentUser: Rider = {
  id: "me",
  username: "elenarossi",
  fullName: "Elena Rossi",
  bio: "Adventure Touring Enthusiast | Weekend Explorer",
  location: "Dhaka, Bangladesh",
  bike: "Ducati DesertX",
  avatar: img.avatarElena,
  cover: img.cover,
  verified: true,
  role: "rider",
  followers: 1200,
  following: 342,
  postsCount: 89,
  ridesCount: 45,
};

export const riders: Rider[] = [
  currentUser,
  {
    id: "elena-r",
    username: "elenarodriguez",
    fullName: "Elena Rodriguez",
    bio: "Coastal touring & group rides",
    location: "Pacific Coast Highway",
    bike: "BMW R1250GS",
    avatar: img.avatarElena,
    cover: img.cover,
    verified: true,
    role: "rider",
    followers: 2400,
    following: 180,
    postsCount: 64,
    ridesCount: 31,
  },
  {
    id: "sarah",
    username: "sarahj",
    fullName: "Sarah Jenkins",
    bio: "Touring Enthusiast",
    location: "Dhaka",
    bike: "Royal Enfield Himalayan",
    avatar: img.avatarSarah,
    cover: img.cover,
    verified: true,
    role: "rider",
    followers: 860,
    following: 210,
    postsCount: 41,
    ridesCount: 22,
  },
  {
    id: "mia",
    username: "miat",
    fullName: "Mia T.",
    bio: "Sport touring",
    location: "Chattogram",
    bike: "Kawasaki Ninja 650",
    avatar: img.avatarMia,
    cover: img.cover,
    verified: false,
    role: "rider",
    followers: 420,
    following: 190,
    postsCount: 28,
    ridesCount: 14,
  },
  {
    id: "alex",
    username: "alexchen",
    fullName: "Alex Chen",
    bio: "Sportbike Enthusiast",
    location: "Sylhet",
    bike: "Yamaha R7",
    avatar: img.avatarAlex,
    cover: img.cover,
    verified: false,
    role: "rider",
    followers: 980,
    following: 140,
    postsCount: 52,
    ridesCount: 19,
  },
  {
    id: "jenna",
    username: "jennak",
    fullName: "Jenna K.",
    bio: "Urban commuter",
    location: "Dhaka",
    bike: "Honda CB350",
    avatar: img.avatarJenna,
    cover: img.cover,
    verified: false,
    role: "rider",
    followers: 310,
    following: 88,
    postsCount: 16,
    ridesCount: 9,
  },
  {
    id: "maya",
    username: "mayak",
    fullName: "Maya Kapoor",
    bio: "Route planner",
    location: "Northern District",
    bike: "Triumph Tiger 900",
    avatar: img.avatarMaya,
    cover: img.cover,
    verified: true,
    role: "rider",
    followers: 540,
    following: 201,
    postsCount: 33,
    ridesCount: 17,
  },
];

export const stories: Story[] = [
  { id: "s1", name: "Sarah J.", avatar: img.avatarSarah },
  { id: "s2", name: "Mia T.", avatar: img.avatarMia },
  { id: "s3", name: "Jenna K.", avatar: img.avatarJenna },
  { id: "s4", name: "Alex W.", avatar: img.storyBike, viewed: true },
  { id: "s5", name: "MotoCrew", avatar: img.storyCrew },
];

export const initialPosts: FeedPost[] = [
  {
    id: "p1",
    author: riders[1],
    content:
      "Perfect conditions today on the PCH. The new suspension setup is handling the curves like a dream. Anyone down for a group ride this weekend? 🌊🏍️ #CoastalRide #TouringLife",
    image: img.pch,
    location: "Malibu, CA",
    createdAt: "2 hours ago",
    likes: 248,
    comments: 42,
    likerAvatars: [img.avatarSarah, img.avatarMia, img.avatarAlex],
  },
  {
    id: "p2",
    author: currentUser,
    content:
      "Incredible morning ride through the coastal canyons. The fog lifted just as we hit the peak. Highly recommend this route to anyone looking for smooth curves and minimal traffic! 🏍️💨 #SundayRide #CoastalCruising",
    image: img.canyon,
    location: "Cox's Bazar Road",
    createdAt: "5 hours ago",
    likes: 245,
    comments: 18,
    likerAvatars: [img.avatarJenna, img.avatarMaya, img.avatarSarah],
    liveRoute: true,
  },
];

export const communities: Community[] = [
  {
    id: "c1",
    name: "Dhaka Riders",
    location: "Dhaka, Central",
    description:
      "The premier community for female riders in the capital. We focus on city meetups, weekend escapes, and technical workshops.",
    cover: img.dhaka,
    members: 1200,
    activity: "Very Active",
    category: "Meetup",
    memberAvatars: [img.avatarSarah, img.avatarJenna],
  },
  {
    id: "c2",
    name: "Chattogram Coastal",
    location: "Chattogram Division",
    description:
      "Embrace the sea breeze. This group specializes in scenic coastal routes, long-distance touring, and building strong sisterhood.",
    cover: img.chittagong,
    members: 850,
    activity: "Active",
    category: "Touring",
    requested: true,
    memberAvatars: [img.avatarMia, img.avatarAlex],
  },
  {
    id: "c3",
    name: "Sylhet Explorers",
    location: "Sylhet Region",
    description:
      "Navigating the beautiful hills and tea gardens. We organize monthly group tours and focus on safe mountain riding techniques.",
    cover: img.sylhet,
    members: 420,
    category: "Touring",
    memberAvatars: [img.avatarMaya, img.avatarAmanda],
  },
  {
    id: "c4",
    name: "West Coast Touring",
    location: "National",
    description: "Long-distance touring sisterhood for multi-day coastal and highway rides.",
    cover: img.coastalGroup,
    members: 2100,
    activity: "Very Active",
    category: "Touring",
    joined: true,
    memberAvatars: [img.avatarElena, img.avatarSarah],
  },
];

export const events: RideEvent[] = [
  {
    id: "e0",
    title: "Pacific Coast Weekend Escape",
    description:
      "A fully curated 3-day ride along the iconic Pacific Coast Highway. Includes premium lodging, planned scenic stops, and evening networking dinners.",
    kind: "Tour",
    location: "Pacific Coast Highway",
    month: "OCT",
    day: "12",
    dateLabel: "October 12 - 14, 2024",
    attending: 27,
    cover: img.coastalGroup,
    featured: true,
  },
  {
    id: "e1",
    title: "Sunset Canyon Run",
    description: "Golden-hour canyon ride with a scenic overlook meetup.",
    kind: "Ride",
    location: "Los Angeles",
    month: "OCT",
    day: "14",
    dateLabel: "October 14",
    attending: 12,
    cover: img.canyon,
  },
  {
    id: "e2",
    title: "Essential Maintenance Workshop",
    description:
      "Learn the basics of chain tensioning, fluid checks, and tire maintenance in a supportive, hands-on environment.",
    kind: "Workshop",
    location: "Dhaka Garage Collective",
    month: "OCT",
    day: "18",
    dateLabel: "October 18",
    attending: 12,
    cover: img.workshop,
  },
  {
    id: "e3",
    title: "Women's Track Day",
    description: "Closed-course coaching and open lapping for licensed riders.",
    kind: "Ride",
    location: "Willow Springs",
    month: "OCT",
    day: "22",
    dateLabel: "October 22",
    attending: 45,
    cover: img.canyon,
  },
  {
    id: "e4",
    title: "Sunday Morning Coffee Run",
    description:
      "A casual, short-distance urban ride ending at the new artisanal roastery downtown. Perfect for new members.",
    kind: "Meetup",
    location: "Dhanmondi",
    month: "OCT",
    day: "22",
    dateLabel: "October 22",
    attending: 35,
    cover: img.coffee,
  },
  {
    id: "e5",
    title: "Advanced Canyon Carving",
    description:
      "For experienced riders looking to refine their cornering techniques on some of the best local twisties.",
    kind: "Ride",
    location: "Bandarban",
    month: "NOV",
    day: "05",
    dateLabel: "November 5",
    attending: 8,
    cover: img.canyon,
  },
  {
    id: "e6",
    title: "Mastering Suspension Setup",
    description:
      "Join our top engineers for a deep dive into dialing in your ride for the perfect balance of comfort and performance.",
    kind: "Workshop",
    location: "Virtual",
    month: "OCT",
    day: "24",
    dateLabel: "October 24 • 7:00 PM",
    attending: 90,
    cover: img.workshop,
  },
];

export const conversations: Conversation[] = [
  {
    id: "cv1",
    name: "Sarah Jenkins",
    avatar: img.avatarSarah,
    preview: "Are we still meeting at the diner before the canyon run?",
    time: "10:42 AM",
    unread: true,
    online: true,
  },
  {
    id: "cv2",
    name: "Weekend Coast Runners",
    avatar: img.storyCrew,
    preview: "Elena: I'll bring the extra toolkit just in case.",
    time: "Yesterday",
    group: true,
  },
  {
    id: "cv3",
    name: "Maya Kapoor",
    initials: "MK",
    preview: "Thanks for the route recommendation!",
    time: "Tue",
  },
  {
    id: "cv4",
    name: "Tech & Gear Group",
    avatar: img.dash,
    preview: "Photo",
    time: "Mon",
    group: true,
  },
];

export const chatThread: ChatMessage[] = [
  { id: "m1", fromMe: false, text: "Hey! Just checking the weather for tomorrow's ride. Looks perfect. ☀️", time: "10:30 AM" },
  { id: "m2", fromMe: true, text: "I saw that! I'm doing a quick oil check tonight but I'm ready to roll.", time: "10:35 AM" },
  { id: "m3", fromMe: true, image: img.garage, time: "10:36 AM" },
  { id: "m4", fromMe: false, voice: true, time: "10:42 AM" },
];

export const notifications: AppNotification[] = [
  {
    id: "n1",
    actor: "Sarah Jenkins",
    avatar: img.avatarSarah,
    body: "liked your coastal canyon post",
    time: "12m",
    unread: true,
    href: "/home",
  },
  {
    id: "n2",
    actor: "Dhaka Riders",
    avatar: img.dhaka,
    body: "New meetup: Sunday Morning Coffee Run",
    time: "1h",
    unread: true,
    href: "/events",
  },
  {
    id: "n3",
    actor: "Alex Chen",
    avatar: img.avatarAlex,
    body: "started following you",
    time: "3h",
    href: "/profile/alex",
  },
  {
    id: "n4",
    actor: "Maya Kapoor",
    avatar: img.avatarMaya,
    body: "commented: “Saving this route!”",
    time: "Yesterday",
    href: "/home",
  },
];

export const trendingHashtags: Hashtag[] = [
  { tag: "#SheRides", posts: "12.4k" },
  { tag: "#WomenWhoRide", posts: "8.1k" },
  { tag: "#CoastalRide", posts: "3.6k" },
  { tag: "#DhakaRiders", posts: "2.2k" },
  { tag: "#TouringLife", posts: "1.9k" },
];

export const sidebarCommunities = [
  { name: "West Coast Touring", href: "/groups" },
  { name: "Dhaka Riders", href: "/groups" },
  { name: "Touring Vets", href: "/groups" },
];

export function findRider(id: string) {
  return riders.find((r) => r.id === id || r.username === id) ?? currentUser;
}
